remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: jwiaduck.github.io
description: A website to share my projects, work, thoughts, and whatever else I deem worthy.
show_downloads: false
google_analytics: G-L8XPV30859